name: Push to GCR GitHub Action
on: workflow_dispatch
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: |
          ls -a
          cd flask
          ls -a
          cat 
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.AUTH_TO_GCP }}
          registry: gcr.io
          project_id: flask
          image_name: server-end
          dockerfile: /home/runner/work/k8s/k8s/flask/Dockerfile
