name: destr

on:
  workflow_dispatch
  #push:
    #branches: [ "main" ]


jobs:
  setup-build-publish-deploy:
    name: ci cd
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: echo
      run: echo '${{ secrets.DOCKER_PUSH }}' >> key.json

    - name: login
      run: gcloud auth activate-service-account doker-pull-push@celtic-beacon-387519.iam.gserviceaccount.com --key-file=./key.json
        
    - name: terraform init
      run: terraform init
      
    - name: terraform plan terraform destroy
      run: terraform plan
       
    - name: terraform destroy
      run: terraform destroy
