name: test
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd
    - name: doker build
      run: sudo docker build -t testapp .
      
    - name: docker run
      run: sudo docker run --rm -p 5000:5000 testapp
