name: test
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone
      uses: actions/checkout@v1 
    - name: doker build
      run: sudo docker build -t testapp /home/runner/work/k8s/k8s/flask
    - name: run
      run: sudo docker run -p 5000:5000 testapp
